### ISSUE TITLE
Compatibility to `qs`

### ISSUE THREAD

**Issue by TheDevMinerTV** [43081j/picoquery#42]
I'm trying to replace `qs` in `express` at the moment in https://github.com/expressjs/express/issues/5723 but the query string tests are failing / succeeding depending on which nesting and array syntax I use.
Could there be some option to support all of the syntaxes?

Here's the tests in question: https://github.com/expressjs/express/blob/5.x/test/req.query.js

**Comment by 43081j** [comment]
assuming this is the test which fails:

```
?foo[0][bar]=baz&foo[0][fizz]=buzz&foo[]=done!
```

it is pretty much `nestingSyntax: 'index'` but with `arrayRepeat: true, arrayRepeatSyntax: 'bracket'`.

although i sense there's a bug in picoquery preventing array repetition syntax from working in this situation

**Comment by TheDevMinerTV** [comment]
<table>
<tr>
<td></td>
<td>

`js`

</td><td>

`index`

</td><td>

`dot`

</td>
</tr>
<tr>
<td>

`bracket`

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
- {
    foo: [
+     [
-     {
        bar: 'baz',
        fizz: 'buzz'
+     ],
+     '': 'done!'
-     },
-     'done!'
    ]
  }
```

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
- {
    foo: [
      {
        bar: 'baz',
        fizz: 'buzz'
      },
+     '': 'done!'
-     'done!'
    ]
  }
```

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
+   'foo[0][bar]': 'baz',
+   'foo[0][fizz]': 'buzz',
+   foo: 'done!'
- {
-   foo: [
-     {
-       bar: 'baz',
-       fizz: 'buzz'
-     },
-     'done!'
-   ]
  }
```

</tr>
<tr>
<td>

`repeat`

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
- {
    foo: [
+     [
-     {
        bar: 'baz',
        fizz: 'buzz'
+     ],
+     '': 'done!'
-     },
-     'done!'
    ]
  }
```

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
- {
    foo: [
      {
        bar: 'baz',
        fizz: 'buzz'
      },
+     '': 'done!'
-     'done!'
    ]
  }
```

</td>
<td>

```diff
+ Empty <[Object: null prototype] {}> {
+   'foo[0][bar]': 'baz',
+   'foo[0][fizz]': 'buzz',
+   'foo[]': 'done!'
- {
-   foo: [
-     {
-       bar: 'baz',
-       fizz: 'buzz'
-     },
-     'done!'
-   ]
  }
```

</td>
</tr>
</table>

Also, would it be possible to also export the `Empty` class or just return a POJO? Otherwise testing will be super annoying because we can't properly use `deepStrictEqual` since that also checks the prototype IIRC.

**Comment by 43081j** [comment]
it is a bug for sure

i can fix the example here but i've also run into another meanwhile. so just taking a look at that before i push a fix 👍
